import type { Metadata } from "next";
import { Inter, Roboto, Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/myComponents/navBar";

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Premier IB Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-[#fff9e6]`}>
        <div className="head flex justify-center items-center">
        </div>
        {children}
      </body>
    </html>
  );
}
